# Generated by Django 3.2.8 on 2021-10-10 20:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'followed_user')},
            },
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='product_description',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='review',
            name='product_title',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='review',
            name='product_type',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Article', 'Article')], default='Livre', max_length=8),
        ),
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='headline',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
