# Generated by Django 3.2.8 on 2021-10-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_review_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
